title: "telâfi"
description: "İhmal edilmiş ne varsa."
url: "https://telafi.org"
baseurl: ""
lang: "tr"
timezone: "America/Phoenix"
permalink: /yazi/:title/
markdown: kramdown
future: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Telafi"
      category: "Yazı"
      reading_time: "6 dk"
      featured: false

exclude:
  - README.md
  - YAZI-EKLEME.md
